services:
  screeps-server:
    image: miniball/screeps-server
    volumes:
      - D:/screeps/mini-world/docker/screeps-server/server:/screeps:rw
    depends_on:
      - mongo
      - redis
    ports:
      - 21025:21025
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
    command: ["npx", "screeps", "start"]

  mongo:
    image: mongo:latest
    volumes:
      - D:/screeps/mini-world/docker/screeps-server/data/db:/data/db:rw
    expose:
      - 27017

  redis:
    image: redis:3.0.6
    volumes:
      - D:/screeps/mini-world/docker/screeps-server/data:/data
    expose:
      - 6379
